apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachineService
metadata:
  name: vm-lb-y3jz
spec:
  selector:
    vm-lb-y3jz: vm-lb-selector
  type: LoadBalancer
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
