apiVersion: v1
kind: Service
metadata:
  name: external-dns-test
  annotations:
    # This tells ExternalDNS which hostname to create in Technitium
    external-dns.alpha.kubernetes.io/hostname: test-service.site-a.vcf.lab
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
