---
#! use tlsConfig to enable TLS connection with BIND server
#! and require BIND server enables TLS meanwhile
#! if we keep use nonTLS connection, comment or remove the tlsConfig part
tlsConfig:
  tls_enable: true
  #! User require to provide base64 encryption format of root ca.crt value 
  #! which uses to validate tls connection with DNS server once tls_enable=true
  ca_crt: "LS0tLS1CRUdJT"
deployment:
  args:
    - --registry=txt
    - --policy=sync
    - --txt-prefix=external-dns-
    - --txt-owner-id=k8s
    - --provider=rfc2136
    - --rfc2136-host=<BIND_SERVER_ADDRESS>    #! update the bind DNS server ip accordingly
    - --rfc2136-port=53
    - --rfc2136-zone=k8s.ex.bc.com     #! update this domain according to your own bind server zone configuration
    - --rfc2136-tsig-secret=<BIND_SERVER_USED_TSIG_SECRET_VALUE>   #! update the tsig secret when deploy bind server uses
    - --rfc2136-tsig-secret-alg=hmac-sha256
    - --rfc2136-tsig-keyname=externaldns-key    #! update this TSIG key name when setup BIND server uses
    - --rfc2136-tsig-axfr
    - --source=service
    - --source=ingress
    - --source=contour-httpproxy     #! If do not install Contour, please remove this support parameter
    - --domain-filter=k8s.ex.bc.com
    - --log-level=debug      #! Use to debug, do not set by deafult is "info" level

