apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: consumption-operator.dsm.vsphere.vmware.com.9.0.1+vmware.0.24913742
spec:
  refName: consumption-operator.dsm.vsphere.vmware.com
  version: 9.0.1+vmware.0.24913742
  releasedAt: "2025-08-15T02:44:09Z"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.packages.broadcom.com/vsphere/dsm-consumption-operator/dsm-consumption-operator-supervisor:9.0.1.0.24913742
      template:
        - ytt:
            ignoreUnknownComments: true
            paths:
              - config/
        - kbld:
            paths:
              - .imgpkg/images.yml
              - "-"
      deploy:
        - kapp: {}
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: consumption-operator.dsm.vsphere.vmware.com
spec:
  displayName: Data Services Manager Consumption Operator
  shortDescription: DSM
